typedef struct _TopDownActivateInfo
{
    BOOLEAN  bActivate;
    ULONG FlagsOffset;
    ULONG VmTopDownBitPosition;
} TOPDOWN_ACTIVATE_INFO, *PTOPDOWN_ACTIVATE_INFO;

typedef struct _TopDownFilenameInfo
{
    USHORT Length; // in bytes
    wchar_t Buffer[1];
} TOPDOWN_FILENAME_INFO, *PTOPDOWN_FILENAME_INFO;

#define FILE_DEVICE_UNKNOWN             0x00000022
#define IOCTL_UNKNOWN_BASE              FILE_DEVICE_UNKNOWN
#define IOCTL_TOPDOWN_ACTIVATE_MONITORING    \
    CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0800, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_TOPDOWN_ADD_FILENAME    \
    CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0801, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
#define IOCTL_TOPDOWN_REMOVE_FILENAME    \
    CTL_CODE(IOCTL_UNKNOWN_BASE, 0x0802, METHOD_BUFFERED, FILE_READ_ACCESS | FILE_WRITE_ACCESS)
